## numPy 002 :: 

In [2]:
import numpy as np

#### Basics

In [67]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [68]:
b = np.array([[3,45,6,5.4,4],[3,5,6,7,8]])
print(b)

[[ 3.  45.   6.   5.4  4. ]
 [ 3.   5.   6.   7.   8. ]]


In [69]:
#get dimension
a.ndim

1

In [70]:
#get shape
b.shape

(2, 5)

In [71]:
# get type
a.dtype

dtype('int16')

In [72]:
# get size
a.itemsize

2

In [73]:
#total size
a.nbytes

6

#### Accessing/Changing specific elements,row, columns, etc.

In [74]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [75]:
# get a specific element [r,c]
a[1,5]

13

In [76]:
# get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [77]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [78]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]
a[0,1:-1:2] # use of negative index 
#both do same work

array([2, 4, 6])

In [79]:
a[1,5] =20
print(a)
a[:,2] = [1,3]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  3 11 12 20 14]]


*3D example!

In [80]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [81]:
#get specific element (work outside in)
b[0,1,1]

4

In [82]:
# replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initializing Different Types of arrays

In [83]:
# All 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [84]:
# All 1's matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [85]:
#Any other Number array
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [86]:
#any other number ( full like) array
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [87]:
#random decimal numbers
np.random.rand(4,2,3)

array([[[0.12320817, 0.39178241, 0.56805247],
        [0.98680432, 0.76016167, 0.33998796]],

       [[0.04790675, 0.96931535, 0.25870662],
        [0.16203594, 0.06044804, 0.00508356]],

       [[0.64574287, 0.54392503, 0.49741989],
        [0.17141876, 0.41770253, 0.50254643]],

       [[0.0995011 , 0.087361  , 0.23726588],
        [0.36675131, 0.94119434, 0.63531609]]])

In [88]:
np.random.random_sample(a.shape)

array([[0.13248892, 0.61986313, 0.96225361, 0.26181579, 0.29790621,
        0.36349012, 0.21882765],
       [0.1610063 , 0.16082953, 0.52433231, 0.49436822, 0.0633343 ,
        0.97277948, 0.97451866]])

In [89]:
# Random Integer Values
np.random.randint(-4,7,size=(3,3))

array([[ 1, -3,  1],
       [-2,  6, -1],
       [-2, -2, -4]])

In [90]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [92]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [4]:
a = np.array([1,2,3])
b=a.copy() # b=a do not direct assign value
b[0] = 100
print(a)

[1 2 3]


Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a-2

array([-1,  0,  1,  2])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
np.min(stats, axis=0)

array([1, 2, 3])

In [65]:
np.max(stats)

6

In [96]:
np.sum(stats, axis=0)

array([5, 7, 9])

### reorganizing arrays

In [98]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [101]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous
* Load Data from File

In [109]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

##### boolean masking and advanced indexing

In [110]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [111]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [115]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [113]:
## you can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [119]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])